FROM python:3.9
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY log_consumer.py .
COPY metrics_generator.py .
COPY db_init.py .
CMD ["sh", "-c", "sleep 60 && python db_init.py && python log_consumer.py"]
